### ISSUE TITLE
[Feature] 상품별 각 연령대 가입자 수 - 막대 그래프

### ISSUE THREAD

**Issue by LimEunSang** [BangCrush/BankAI-Admin#2]
## 📌 Issue

- 상품별 각 연령대 가입자 수 - 막대 그래프

## 📜 To-do

- [x] [구글차트](https://developers.google.com/chart?hl=ko) 또는 [하이차트](https://www.highcharts.com/?gad_source=1&gclid=Cj0KCQjw0_WyBhDMARIsAL1Vz8u90tWA7sW8od0mYJiXii6pmeZ9sUbgIBbuTZnyb1FyEolRelZySx4aAqz2EALw_wcB) 또는 [react-chartjs-2](https://zindex.tistory.com/300)에서 차트 고르기
  - [HorizontalBarChart](https://react-chartjs-2.js.org/examples/horizontal-bar-chart)
- [x] 차트 데이터 형식 확인
- [x] 상품별 가입자 정보 조회 API 생성
- [x] 차트 완성하기
- [x] 페이지 라우팅
- [x] side-nav 추가
- [ ] 처음 페이지 로딩 시 API 완료 전에 component를 불러오는 순서 문제 해결
